spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300 #配置java访问elasticsearch端口
      repositories:
        enabled: true
      cluster-name: elasticsearch #需与elasticsearch配置文件的名字一致，也可以不配置