spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300 #配置java访问elasticsearch端口
      repositories:
        enabled: true
      cluster-name: elasticsearch #需与elasticsearch配置文件的名字一致，也可以不配置
  application:
    name: postgres
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5432/test

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.springbootdata.test.postgres.entity

#showSql
logging:
  level:
    com:
      springbootdata:
        test:
          postgres:
            mapper: debug
